const MEBIBYTE = 1024 * 1024;

export const MAX_IMAGE_FILE_SIZE_MB = 25;
export const MAX_VIDEO_FILE_SIZE_MB = 800;

export const MAX_IMAGE_FILE_SIZE = MAX_IMAGE_FILE_SIZE_MB * MEBIBYTE;
export const MAX_VIDEO_FILE_SIZE = MAX_VIDEO_FILE_SIZE_MB * MEBIBYTE;
